/**
 * PIM Sector Definitions
 * Each sector defines the catalogs, product types, and attribute templates
 * available for that industry vertical.
 *
 * Every product type includes comprehensive, real-world attributes:
 * - Fashion: regional sizing (EU/US/UK), fabric GSM, care labels, gender
 * - Home: materials, textures, coatings, heat resistance, dimensions
 * - Electronics: full specs, connectivity, power
 * - Food: nutrition, allergens, certifications
 * - Industrial: compliance, safety, tolerances
 * - Beauty: ingredients, skin compatibility, certifications
 */

export type AttributeType =
  | "TEXT"
  | "NUMBER"
  | "BOOLEAN"
  | "SELECT"
  | "MULTISELECT"
  | "DATE"
  | "RICH_TEXT"
  | "URL"
  | "COLOR";

export type Sector =
  | "ELECTRONICS"
  | "FASHION"
  | "FOOD"
  | "INDUSTRIAL"
  | "HOME"
  | "BEAUTY"
  | "AUTOMOTIVE";

export interface AttributeTemplate {
  name: string;
  slug: string;
  type: AttributeType;
  unit?: string;
  isRequired?: boolean;
  isFilterable?: boolean;
  isSearchable?: boolean;
  showOnCard?: boolean;
  options?: string[];
  validation?: { min?: number; max?: number; pattern?: string };
  group: string;
}

export interface ProductTypeTemplate {
  name: string;
  slug: string;
  description: string;
  icon?: string;
  attributes: AttributeTemplate[];
}

export interface SectorDefinition {
  name: string;
  slug: string;
  sector: Sector;
  description: string;
  attributeGroups: { name: string; slug: string }[];
  productTypes: ProductTypeTemplate[];
}

// ─── ELECTRONICS ────────────────────────────────────────────────

export const electronicsSector: SectorDefinition = {
  name: "Electronics",
  slug: "electronics",
  sector: "ELECTRONICS",
  description: "Consumer electronics, computers, phones, and accessories",
  attributeGroups: [
    { name: "Technical Specs", slug: "technical-specs" },
    { name: "Display", slug: "display" },
    { name: "Battery & Power", slug: "battery-power" },
    { name: "Connectivity", slug: "connectivity" },
    { name: "Physical", slug: "physical" },
  ],
  productTypes: [
    {
      name: "Laptop",
      slug: "laptop",
      description: "Portable computers",
      icon: "laptop",
      attributes: [
        {
          name: "Processor",
          slug: "processor",
          type: "TEXT",
          group: "technical-specs",
          isRequired: true,
          isFilterable: true,
          isSearchable: true,
        },
        {
          name: "RAM",
          slug: "ram",
          type: "NUMBER",
          unit: "GB",
          group: "technical-specs",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Storage",
          slug: "storage",
          type: "NUMBER",
          unit: "GB",
          group: "technical-specs",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Storage Type",
          slug: "storage-type",
          type: "SELECT",
          options: ["SSD", "HDD", "NVMe SSD"],
          group: "technical-specs",
          isFilterable: true,
        },
        {
          name: "Screen Size",
          slug: "screen-size",
          type: "NUMBER",
          unit: "inch",
          group: "display",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Resolution",
          slug: "resolution",
          type: "SELECT",
          options: ["1920x1080", "2560x1440", "3840x2160", "2560x1600"],
          group: "display",
          isFilterable: true,
        },
        {
          name: "Panel Type",
          slug: "panel-type",
          type: "SELECT",
          options: ["IPS", "OLED", "VA", "TN"],
          group: "display",
          isFilterable: true,
        },
        {
          name: "Battery Capacity",
          slug: "battery-capacity",
          type: "NUMBER",
          unit: "Wh",
          group: "battery-power",
        },
        {
          name: "Battery Life",
          slug: "battery-life",
          type: "NUMBER",
          unit: "hours",
          group: "battery-power",
          showOnCard: true,
        },
        {
          name: "WiFi",
          slug: "wifi",
          type: "SELECT",
          options: ["WiFi 5", "WiFi 6", "WiFi 6E", "WiFi 7"],
          group: "connectivity",
        },
        {
          name: "Bluetooth",
          slug: "bluetooth",
          type: "SELECT",
          options: ["5.0", "5.1", "5.2", "5.3"],
          group: "connectivity",
        },
        { name: "USB Ports", slug: "usb-ports", type: "TEXT", group: "connectivity" },
        {
          name: "Weight",
          slug: "weight",
          type: "NUMBER",
          unit: "kg",
          group: "physical",
          isFilterable: true,
        },
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "physical",
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Operating System",
          slug: "os",
          type: "SELECT",
          options: ["Windows 11", "macOS", "ChromeOS", "Linux"],
          group: "technical-specs",
          isFilterable: true,
        },
      ],
    },
    {
      name: "Smartphone",
      slug: "smartphone",
      description: "Mobile phones and smartphones",
      icon: "smartphone",
      attributes: [
        {
          name: "Processor",
          slug: "processor",
          type: "TEXT",
          group: "technical-specs",
          isRequired: true,
          isSearchable: true,
        },
        {
          name: "RAM",
          slug: "ram",
          type: "NUMBER",
          unit: "GB",
          group: "technical-specs",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Storage",
          slug: "storage",
          type: "NUMBER",
          unit: "GB",
          group: "technical-specs",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Screen Size",
          slug: "screen-size",
          type: "NUMBER",
          unit: "inch",
          group: "display",
          isRequired: true,
          isFilterable: true,
        },
        { name: "Resolution", slug: "resolution", type: "TEXT", group: "display" },
        {
          name: "Refresh Rate",
          slug: "refresh-rate",
          type: "NUMBER",
          unit: "Hz",
          group: "display",
          isFilterable: true,
        },
        {
          name: "Main Camera",
          slug: "main-camera",
          type: "NUMBER",
          unit: "MP",
          group: "technical-specs",
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Battery Capacity",
          slug: "battery-capacity",
          type: "NUMBER",
          unit: "mAh",
          group: "battery-power",
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Fast Charging",
          slug: "fast-charging",
          type: "NUMBER",
          unit: "W",
          group: "battery-power",
        },
        { name: "5G", slug: "5g", type: "BOOLEAN", group: "connectivity", isFilterable: true },
        { name: "NFC", slug: "nfc", type: "BOOLEAN", group: "connectivity" },
        {
          name: "Water Resistance",
          slug: "water-resistance",
          type: "SELECT",
          options: ["IP67", "IP68", "None"],
          group: "physical",
          isFilterable: true,
        },
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "physical",
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Operating System",
          slug: "os",
          type: "SELECT",
          options: ["Android 14", "Android 15", "iOS 17", "iOS 18"],
          group: "technical-specs",
          isFilterable: true,
        },
      ],
    },
    {
      name: "Headphones",
      slug: "headphones",
      description: "Audio headphones and earbuds",
      icon: "headphones",
      attributes: [
        {
          name: "Type",
          slug: "type",
          type: "SELECT",
          options: ["Over-ear", "On-ear", "In-ear", "True Wireless"],
          group: "technical-specs",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Noise Cancelling",
          slug: "noise-cancelling",
          type: "BOOLEAN",
          group: "technical-specs",
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Driver Size",
          slug: "driver-size",
          type: "NUMBER",
          unit: "mm",
          group: "technical-specs",
        },
        {
          name: "Frequency Response",
          slug: "frequency-response",
          type: "TEXT",
          group: "technical-specs",
        },
        {
          name: "Battery Life",
          slug: "battery-life",
          type: "NUMBER",
          unit: "hours",
          group: "battery-power",
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Wireless",
          slug: "wireless",
          type: "BOOLEAN",
          group: "connectivity",
          isFilterable: true,
        },
        {
          name: "Bluetooth Version",
          slug: "bluetooth",
          type: "SELECT",
          options: ["5.0", "5.1", "5.2", "5.3", "5.4"],
          group: "connectivity",
        },
        {
          name: "Codec Support",
          slug: "codec-support",
          type: "MULTISELECT",
          options: ["SBC", "AAC", "aptX", "aptX HD", "LDAC", "LC3"],
          group: "connectivity",
        },
        { name: "Weight", slug: "weight", type: "NUMBER", unit: "g", group: "physical" },
        { name: "Color", slug: "color", type: "COLOR", group: "physical", isFilterable: true },
      ],
    },
  ],
};

// ─── FASHION ────────────────────────────────────────────────────

export const fashionSector: SectorDefinition = {
  name: "Fashion & Apparel",
  slug: "fashion",
  sector: "FASHION",
  description: "Clothing, shoes, and accessories",
  attributeGroups: [
    { name: "Sizing", slug: "sizing" },
    { name: "Regional Sizes", slug: "regional-sizes" },
    { name: "Material & Composition", slug: "material" },
    { name: "Style", slug: "style" },
    { name: "Care & Maintenance", slug: "care" },
  ],
  productTypes: [
    {
      name: "T-Shirt",
      slug: "tshirt",
      description: "Casual t-shirts and tops",
      icon: "shirt",
      attributes: [
        // Sizing
        {
          name: "Size (International)",
          slug: "size",
          type: "SELECT",
          options: ["XXS", "XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL"],
          group: "sizing",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Size (EU)",
          slug: "size-eu",
          type: "SELECT",
          options: ["44", "46", "48", "50", "52", "54", "56", "58", "60"],
          group: "regional-sizes",
        },
        {
          name: "Size (US)",
          slug: "size-us",
          type: "SELECT",
          options: ["2", "4", "6", "8", "10", "12", "14", "16", "18"],
          group: "regional-sizes",
        },
        {
          name: "Size (UK)",
          slug: "size-uk",
          type: "SELECT",
          options: ["6", "8", "10", "12", "14", "16", "18", "20", "22"],
          group: "regional-sizes",
        },
        {
          name: "Gender",
          slug: "gender",
          type: "SELECT",
          options: ["Men", "Women", "Unisex", "Kids"],
          group: "sizing",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Fit",
          slug: "fit",
          type: "SELECT",
          options: ["Regular", "Slim", "Oversized", "Relaxed", "Cropped", "Longline"],
          group: "sizing",
          isFilterable: true,
        },
        { name: "Chest Width", slug: "chest-width", type: "NUMBER", unit: "cm", group: "sizing" },
        { name: "Body Length", slug: "body-length", type: "NUMBER", unit: "cm", group: "sizing" },
        {
          name: "Sleeve Length",
          slug: "sleeve-length",
          type: "NUMBER",
          unit: "cm",
          group: "sizing",
        },
        // Material
        {
          name: "Primary Fabric",
          slug: "primary-fabric",
          type: "SELECT",
          options: [
            "Cotton",
            "Organic Cotton",
            "Polyester",
            "Linen",
            "Bamboo",
            "Modal",
            "Tencel",
            "Viscose",
            "Hemp",
            "Silk",
          ],
          group: "material",
          isRequired: true,
          isFilterable: true,
        },
        { name: "Fabric Blend", slug: "fabric-blend", type: "TEXT", group: "material" },
        {
          name: "Fabric Weight (GSM)",
          slug: "gsm",
          type: "NUMBER",
          unit: "g/m²",
          group: "material",
          isFilterable: true,
          validation: { min: 80, max: 400 },
        },
        {
          name: "Fabric Texture",
          slug: "fabric-texture",
          type: "SELECT",
          options: [
            "Smooth Jersey",
            "Ribbed",
            "Piqué",
            "Slub",
            "French Terry",
            "Waffle Knit",
            "Interlock",
          ],
          group: "material",
        },
        {
          name: "Stretch",
          slug: "stretch",
          type: "SELECT",
          options: ["No Stretch", "Slight Stretch", "Moderate Stretch", "4-Way Stretch"],
          group: "material",
          isFilterable: true,
        },
        {
          name: "Sustainable",
          slug: "sustainable",
          type: "BOOLEAN",
          group: "material",
          isFilterable: true,
        },
        {
          name: "Certification",
          slug: "certification",
          type: "MULTISELECT",
          options: [
            "GOTS Organic",
            "OEKO-TEX",
            "Fair Trade",
            "BCI Cotton",
            "GRS Recycled",
            "Bluesign",
          ],
          group: "material",
          isFilterable: true,
        },
        // Style
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "style",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Color Name",
          slug: "color-name",
          type: "TEXT",
          group: "style",
          isSearchable: true,
        },
        {
          name: "Pattern",
          slug: "pattern",
          type: "SELECT",
          options: [
            "Solid",
            "Striped",
            "Printed",
            "Graphic",
            "Tie-Dye",
            "Color Block",
            "Heathered",
            "Camo",
          ],
          group: "style",
          isFilterable: true,
        },
        {
          name: "Neck Type",
          slug: "neck-type",
          type: "SELECT",
          options: ["Crew Neck", "V-Neck", "Henley", "Polo", "Scoop", "Mock Neck", "Turtleneck"],
          group: "style",
          isFilterable: true,
        },
        {
          name: "Sleeve Type",
          slug: "sleeve-type",
          type: "SELECT",
          options: [
            "Short Sleeve",
            "Long Sleeve",
            "3/4 Sleeve",
            "Sleeveless",
            "Cap Sleeve",
            "Raglan",
          ],
          group: "style",
          isFilterable: true,
        },
        {
          name: "Hem Style",
          slug: "hem-style",
          type: "SELECT",
          options: ["Straight", "Curved", "Split Side", "Raw Edge", "Banded"],
          group: "style",
        },
        // Care
        {
          name: "Wash Instructions",
          slug: "wash-instructions",
          type: "SELECT",
          options: ["Machine Wash Cold", "Machine Wash Warm", "Hand Wash Only", "Dry Clean Only"],
          group: "care",
        },
        {
          name: "Drying",
          slug: "drying",
          type: "SELECT",
          options: ["Tumble Dry Low", "Hang Dry", "Lay Flat to Dry", "Do Not Tumble Dry"],
          group: "care",
        },
        {
          name: "Ironing",
          slug: "ironing",
          type: "SELECT",
          options: ["Iron Low", "Iron Medium", "Do Not Iron", "Steam Only"],
          group: "care",
        },
        {
          name: "Country of Manufacture",
          slug: "made-in",
          type: "TEXT",
          group: "care",
          isFilterable: true,
        },
      ],
    },
    {
      name: "Pants & Trousers",
      slug: "pants",
      description: "Jeans, chinos, trousers, and shorts",
      icon: "ruler",
      attributes: [
        {
          name: "Waist Size",
          slug: "waist-size",
          type: "NUMBER",
          unit: "inch",
          group: "sizing",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
          validation: { min: 24, max: 50 },
        },
        {
          name: "Inseam Length",
          slug: "inseam",
          type: "NUMBER",
          unit: "inch",
          group: "sizing",
          isRequired: true,
          isFilterable: true,
          validation: { min: 7, max: 36 },
        },
        {
          name: "Size (EU)",
          slug: "size-eu",
          type: "SELECT",
          options: ["38", "40", "42", "44", "46", "48", "50", "52", "54", "56"],
          group: "regional-sizes",
        },
        {
          name: "Size (US)",
          slug: "size-us",
          type: "SELECT",
          options: ["28", "29", "30", "31", "32", "33", "34", "36", "38", "40"],
          group: "regional-sizes",
        },
        {
          name: "Size (UK)",
          slug: "size-uk",
          type: "SELECT",
          options: ["28", "30", "32", "34", "36", "38", "40"],
          group: "regional-sizes",
        },
        {
          name: "Gender",
          slug: "gender",
          type: "SELECT",
          options: ["Men", "Women", "Unisex"],
          group: "sizing",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Fit",
          slug: "fit",
          type: "SELECT",
          options: [
            "Skinny",
            "Slim",
            "Regular",
            "Straight",
            "Relaxed",
            "Wide Leg",
            "Bootcut",
            "Tapered",
          ],
          group: "sizing",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Rise",
          slug: "rise",
          type: "SELECT",
          options: ["Low Rise", "Mid Rise", "High Rise"],
          group: "sizing",
          isFilterable: true,
        },
        {
          name: "Primary Fabric",
          slug: "primary-fabric",
          type: "SELECT",
          options: [
            "Denim",
            "Cotton Twill",
            "Chino Cotton",
            "Linen",
            "Wool",
            "Corduroy",
            "Polyester",
            "Nylon",
            "Fleece",
          ],
          group: "material",
          isRequired: true,
          isFilterable: true,
        },
        { name: "Fabric Blend", slug: "fabric-blend", type: "TEXT", group: "material" },
        {
          name: "Fabric Weight (GSM)",
          slug: "gsm",
          type: "NUMBER",
          unit: "g/m²",
          group: "material",
          validation: { min: 120, max: 500 },
        },
        {
          name: "Stretch",
          slug: "stretch",
          type: "SELECT",
          options: ["No Stretch", "Slight Stretch", "Moderate Stretch", "Super Stretch"],
          group: "material",
          isFilterable: true,
        },
        {
          name: "Denim Wash",
          slug: "denim-wash",
          type: "SELECT",
          options: [
            "Raw/Unwashed",
            "Light Wash",
            "Medium Wash",
            "Dark Wash",
            "Black",
            "Acid Wash",
            "Stonewash",
          ],
          group: "material",
          isFilterable: true,
        },
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "style",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Style Type",
          slug: "style-type",
          type: "SELECT",
          options: [
            "Jeans",
            "Chinos",
            "Dress Pants",
            "Cargo",
            "Joggers",
            "Shorts",
            "Culottes",
            "Leggings",
          ],
          group: "style",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Closure",
          slug: "closure",
          type: "SELECT",
          options: ["Zip Fly + Button", "Button Fly", "Drawstring", "Elastic Waist", "Hook & Bar"],
          group: "style",
        },
        { name: "Pockets", slug: "pockets", type: "NUMBER", group: "style" },
        {
          name: "Wash Instructions",
          slug: "wash-instructions",
          type: "SELECT",
          options: ["Machine Wash Cold", "Machine Wash Warm", "Hand Wash Only", "Dry Clean Only"],
          group: "care",
        },
        {
          name: "Country of Manufacture",
          slug: "made-in",
          type: "TEXT",
          group: "care",
          isFilterable: true,
        },
      ],
    },
    {
      name: "Dress",
      slug: "dress",
      description: "Dresses and gowns",
      icon: "shirt",
      attributes: [
        {
          name: "Size (International)",
          slug: "size",
          type: "SELECT",
          options: ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
          group: "sizing",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Size (EU)",
          slug: "size-eu",
          type: "SELECT",
          options: ["32", "34", "36", "38", "40", "42", "44", "46", "48"],
          group: "regional-sizes",
        },
        {
          name: "Size (US)",
          slug: "size-us",
          type: "SELECT",
          options: ["0", "2", "4", "6", "8", "10", "12", "14", "16"],
          group: "regional-sizes",
        },
        {
          name: "Size (UK)",
          slug: "size-uk",
          type: "SELECT",
          options: ["4", "6", "8", "10", "12", "14", "16", "18", "20"],
          group: "regional-sizes",
        },
        { name: "Bust", slug: "bust", type: "NUMBER", unit: "cm", group: "sizing" },
        { name: "Waist", slug: "waist", type: "NUMBER", unit: "cm", group: "sizing" },
        { name: "Hip", slug: "hip", type: "NUMBER", unit: "cm", group: "sizing" },
        {
          name: "Dress Length",
          slug: "dress-length",
          type: "SELECT",
          options: ["Mini", "Above Knee", "Knee Length", "Midi", "Maxi", "Floor Length"],
          group: "sizing",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Primary Fabric",
          slug: "primary-fabric",
          type: "SELECT",
          options: [
            "Cotton",
            "Silk",
            "Chiffon",
            "Satin",
            "Linen",
            "Polyester",
            "Lace",
            "Velvet",
            "Jersey",
            "Crepe",
            "Organza",
            "Tulle",
          ],
          group: "material",
          isRequired: true,
          isFilterable: true,
        },
        { name: "Fabric Blend", slug: "fabric-blend", type: "TEXT", group: "material" },
        {
          name: "Lining",
          slug: "lining",
          type: "SELECT",
          options: ["Fully Lined", "Partially Lined", "Unlined"],
          group: "material",
        },
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "style",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Pattern",
          slug: "pattern",
          type: "SELECT",
          options: [
            "Solid",
            "Floral",
            "Polka Dot",
            "Striped",
            "Abstract",
            "Animal Print",
            "Plaid",
            "Geometric",
          ],
          group: "style",
          isFilterable: true,
        },
        {
          name: "Neckline",
          slug: "neckline",
          type: "SELECT",
          options: [
            "Round",
            "V-Neck",
            "Sweetheart",
            "Off Shoulder",
            "Halter",
            "Strapless",
            "Square",
            "Boat Neck",
            "Cowl",
          ],
          group: "style",
          isFilterable: true,
        },
        {
          name: "Sleeve Type",
          slug: "sleeve-type",
          type: "SELECT",
          options: [
            "Sleeveless",
            "Spaghetti Strap",
            "Cap Sleeve",
            "Short Sleeve",
            "3/4 Sleeve",
            "Long Sleeve",
            "Bell Sleeve",
            "Puff Sleeve",
          ],
          group: "style",
          isFilterable: true,
        },
        {
          name: "Silhouette",
          slug: "silhouette",
          type: "SELECT",
          options: [
            "A-Line",
            "Bodycon",
            "Shift",
            "Wrap",
            "Fit & Flare",
            "Empire",
            "Sheath",
            "Mermaid",
            "Skater",
          ],
          group: "style",
          isFilterable: true,
        },
        {
          name: "Occasion",
          slug: "occasion",
          type: "MULTISELECT",
          options: ["Casual", "Work", "Evening", "Cocktail", "Wedding Guest", "Beach", "Formal"],
          group: "style",
          isFilterable: true,
        },
        {
          name: "Wash Instructions",
          slug: "wash-instructions",
          type: "SELECT",
          options: [
            "Machine Wash Cold",
            "Hand Wash Only",
            "Dry Clean Only",
            "Dry Clean Recommended",
          ],
          group: "care",
        },
        { name: "Country of Manufacture", slug: "made-in", type: "TEXT", group: "care" },
      ],
    },
    {
      name: "Shoes",
      slug: "shoes",
      description: "Footwear of all types",
      icon: "footprints",
      attributes: [
        // Regional sizing
        {
          name: "Size (EU)",
          slug: "size-eu",
          type: "NUMBER",
          group: "regional-sizes",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
          validation: { min: 18, max: 50 },
        },
        {
          name: "Size (US Men)",
          slug: "size-us-men",
          type: "NUMBER",
          group: "regional-sizes",
          validation: { min: 1, max: 16 },
        },
        {
          name: "Size (US Women)",
          slug: "size-us-women",
          type: "NUMBER",
          group: "regional-sizes",
          validation: { min: 1, max: 14 },
        },
        {
          name: "Size (UK)",
          slug: "size-uk",
          type: "NUMBER",
          group: "regional-sizes",
          validation: { min: 1, max: 15 },
        },
        {
          name: "Size (JP/cm)",
          slug: "size-jp",
          type: "NUMBER",
          unit: "cm",
          group: "regional-sizes",
        },
        {
          name: "Gender",
          slug: "gender",
          type: "SELECT",
          options: ["Men", "Women", "Unisex", "Kids", "Toddler"],
          group: "sizing",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Width",
          slug: "width",
          type: "SELECT",
          options: ["Narrow (B)", "Regular (D)", "Wide (E/EE)", "Extra Wide (EEE/EEEE)"],
          group: "sizing",
          isFilterable: true,
        },
        {
          name: "Arch Support",
          slug: "arch-support",
          type: "SELECT",
          options: ["Flat", "Low", "Medium", "High"],
          group: "sizing",
        },
        // Material
        {
          name: "Upper Material",
          slug: "upper-material",
          type: "SELECT",
          options: [
            "Full Grain Leather",
            "Nubuck",
            "Suede",
            "Canvas",
            "Mesh",
            "Knit",
            "Synthetic Leather",
            "Patent Leather",
            "Gore-Tex",
            "Neoprene",
          ],
          group: "material",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Sole Material",
          slug: "sole-material",
          type: "SELECT",
          options: ["Rubber", "EVA", "Leather", "Crepe", "PU", "Vibram", "Cork", "TPU", "Phylon"],
          group: "material",
        },
        {
          name: "Insole Material",
          slug: "insole-material",
          type: "SELECT",
          options: ["Memory Foam", "Ortholite", "Leather", "EVA", "Cork", "Gel"],
          group: "material",
        },
        {
          name: "Lining",
          slug: "lining",
          type: "SELECT",
          options: ["Leather", "Textile", "Synthetic", "Gore-Tex", "Fur/Shearling", "Unlined"],
          group: "material",
        },
        // Style
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "style",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Style Type",
          slug: "style-type",
          type: "SELECT",
          options: [
            "Sneakers",
            "Running",
            "Boots",
            "Ankle Boots",
            "Chelsea Boots",
            "Sandals",
            "Loafers",
            "Oxford",
            "Derby",
            "Heels",
            "Pumps",
            "Flats",
            "Espadrilles",
            "Mules",
            "Slides",
            "Hiking Boots",
          ],
          group: "style",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Closure",
          slug: "closure",
          type: "SELECT",
          options: ["Laces", "Velcro", "Slip-on", "Zipper", "Buckle", "BOA System", "Elastic"],
          group: "style",
        },
        {
          name: "Toe Shape",
          slug: "toe-shape",
          type: "SELECT",
          options: ["Round", "Pointed", "Square", "Almond", "Open Toe", "Steel Toe"],
          group: "style",
        },
        { name: "Heel Height", slug: "heel-height", type: "NUMBER", unit: "cm", group: "sizing" },
        {
          name: "Heel Type",
          slug: "heel-type",
          type: "SELECT",
          options: ["Flat", "Block", "Stiletto", "Wedge", "Platform", "Kitten", "Stacked"],
          group: "style",
        },
        {
          name: "Waterproof",
          slug: "waterproof",
          type: "BOOLEAN",
          group: "material",
          isFilterable: true,
        },
        { name: "Weight (per shoe)", slug: "weight", type: "NUMBER", unit: "g", group: "sizing" },
        // Care
        { name: "Care Instructions", slug: "care-instructions", type: "TEXT", group: "care" },
        { name: "Country of Manufacture", slug: "made-in", type: "TEXT", group: "care" },
      ],
    },
    {
      name: "Jacket",
      slug: "jacket",
      description: "Outerwear and jackets",
      icon: "shirt",
      attributes: [
        {
          name: "Size",
          slug: "size",
          type: "SELECT",
          options: ["XS", "S", "M", "L", "XL", "XXL"],
          group: "sizing",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Fit",
          slug: "fit",
          type: "SELECT",
          options: ["Regular", "Slim", "Oversized"],
          group: "sizing",
          isFilterable: true,
        },
        {
          name: "Outer Material",
          slug: "outer-material",
          type: "SELECT",
          options: ["Denim", "Leather", "Nylon", "Polyester", "Wool", "Cotton", "Gore-Tex"],
          group: "material",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Lining",
          slug: "lining",
          type: "SELECT",
          options: ["Fleece", "Polyester", "Cotton", "Down", "Synthetic Down", "None"],
          group: "material",
        },
        {
          name: "Insulation",
          slug: "insulation",
          type: "SELECT",
          options: ["None", "Light", "Medium", "Heavy", "Down"],
          group: "material",
          isFilterable: true,
        },
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "style",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Style",
          slug: "jacket-style",
          type: "SELECT",
          options: [
            "Bomber",
            "Parka",
            "Blazer",
            "Denim",
            "Leather",
            "Puffer",
            "Trench",
            "Windbreaker",
          ],
          group: "style",
          isFilterable: true,
        },
        {
          name: "Waterproof",
          slug: "waterproof",
          type: "BOOLEAN",
          group: "material",
          isFilterable: true,
        },
        { name: "Hood", slug: "hood", type: "BOOLEAN", group: "style", isFilterable: true },
        {
          name: "Season",
          slug: "season",
          type: "MULTISELECT",
          options: ["Spring", "Summer", "Autumn", "Winter"],
          group: "style",
          isFilterable: true,
        },
      ],
    },
  ],
};

// ─── FOOD & BEVERAGE ────────────────────────────────────────────

export const foodSector: SectorDefinition = {
  name: "Food & Beverage",
  slug: "food-beverage",
  sector: "FOOD",
  description: "Food products, drinks, and culinary items",
  attributeGroups: [
    { name: "Nutritional Info", slug: "nutritional" },
    { name: "Ingredients & Origin", slug: "ingredients" },
    { name: "Packaging", slug: "packaging" },
    { name: "Dietary", slug: "dietary" },
  ],
  productTypes: [
    {
      name: "Wine",
      slug: "wine",
      description: "Wines and champagne",
      icon: "wine",
      attributes: [
        {
          name: "Type",
          slug: "wine-type",
          type: "SELECT",
          options: ["Red", "White", "Rosé", "Sparkling", "Dessert", "Fortified"],
          group: "ingredients",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Grape Variety",
          slug: "grape-variety",
          type: "MULTISELECT",
          options: [
            "Cabernet Sauvignon",
            "Merlot",
            "Pinot Noir",
            "Chardonnay",
            "Sauvignon Blanc",
            "Riesling",
            "Syrah",
            "Tempranillo",
            "Malbec",
          ],
          group: "ingredients",
          isFilterable: true,
        },
        {
          name: "Region",
          slug: "region",
          type: "TEXT",
          group: "ingredients",
          isRequired: true,
          isFilterable: true,
          isSearchable: true,
        },
        {
          name: "Country",
          slug: "country",
          type: "TEXT",
          group: "ingredients",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Vintage",
          slug: "vintage",
          type: "NUMBER",
          group: "ingredients",
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Alcohol Content",
          slug: "alcohol",
          type: "NUMBER",
          unit: "%",
          group: "ingredients",
          isRequired: true,
        },
        {
          name: "Volume",
          slug: "volume",
          type: "NUMBER",
          unit: "ml",
          group: "packaging",
          isRequired: true,
        },
        { name: "Tasting Notes", slug: "tasting-notes", type: "RICH_TEXT", group: "ingredients" },
        { name: "Food Pairing", slug: "food-pairing", type: "TEXT", group: "ingredients" },
        { name: "Serving Temperature", slug: "serving-temp", type: "TEXT", group: "ingredients" },
        { name: "Organic", slug: "organic", type: "BOOLEAN", group: "dietary", isFilterable: true },
      ],
    },
    {
      name: "Coffee",
      slug: "coffee",
      description: "Coffee beans and grounds",
      icon: "coffee",
      attributes: [
        {
          name: "Roast Level",
          slug: "roast-level",
          type: "SELECT",
          options: ["Light", "Medium-Light", "Medium", "Medium-Dark", "Dark"],
          group: "ingredients",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Origin",
          slug: "origin",
          type: "TEXT",
          group: "ingredients",
          isRequired: true,
          isFilterable: true,
          isSearchable: true,
        },
        {
          name: "Bean Type",
          slug: "bean-type",
          type: "SELECT",
          options: ["Arabica", "Robusta", "Blend"],
          group: "ingredients",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Process",
          slug: "process",
          type: "SELECT",
          options: ["Washed", "Natural", "Honey", "Anaerobic"],
          group: "ingredients",
          isFilterable: true,
        },
        {
          name: "Grind",
          slug: "grind",
          type: "SELECT",
          options: ["Whole Bean", "Espresso", "Filter", "French Press", "Cold Brew"],
          group: "packaging",
          isFilterable: true,
        },
        {
          name: "Weight",
          slug: "weight",
          type: "NUMBER",
          unit: "g",
          group: "packaging",
          isRequired: true,
        },
        {
          name: "Flavor Notes",
          slug: "flavor-notes",
          type: "MULTISELECT",
          options: ["Chocolate", "Fruit", "Nutty", "Floral", "Citrus", "Caramel", "Berry", "Spicy"],
          group: "ingredients",
          isFilterable: true,
        },
        { name: "Altitude", slug: "altitude", type: "TEXT", unit: "masl", group: "ingredients" },
        {
          name: "Fair Trade",
          slug: "fair-trade",
          type: "BOOLEAN",
          group: "dietary",
          isFilterable: true,
        },
        { name: "Organic", slug: "organic", type: "BOOLEAN", group: "dietary", isFilterable: true },
      ],
    },
    {
      name: "Packaged Food",
      slug: "packaged-food",
      description: "Packaged and processed food items",
      icon: "package",
      attributes: [
        {
          name: "Calories",
          slug: "calories",
          type: "NUMBER",
          unit: "kcal",
          group: "nutritional",
          isRequired: true,
        },
        { name: "Protein", slug: "protein", type: "NUMBER", unit: "g", group: "nutritional" },
        { name: "Carbohydrates", slug: "carbs", type: "NUMBER", unit: "g", group: "nutritional" },
        { name: "Fat", slug: "fat", type: "NUMBER", unit: "g", group: "nutritional" },
        { name: "Sugar", slug: "sugar", type: "NUMBER", unit: "g", group: "nutritional" },
        { name: "Fiber", slug: "fiber", type: "NUMBER", unit: "g", group: "nutritional" },
        { name: "Sodium", slug: "sodium", type: "NUMBER", unit: "mg", group: "nutritional" },
        {
          name: "Ingredients List",
          slug: "ingredients-list",
          type: "RICH_TEXT",
          group: "ingredients",
          isRequired: true,
        },
        {
          name: "Allergens",
          slug: "allergens",
          type: "MULTISELECT",
          options: ["Gluten", "Dairy", "Nuts", "Soy", "Eggs", "Fish", "Shellfish", "Sesame"],
          group: "dietary",
          isFilterable: true,
        },
        {
          name: "Dietary",
          slug: "dietary-type",
          type: "MULTISELECT",
          options: ["Vegan", "Vegetarian", "Gluten-Free", "Keto", "Paleo", "Halal", "Kosher"],
          group: "dietary",
          isFilterable: true,
        },
        {
          name: "Net Weight",
          slug: "net-weight",
          type: "NUMBER",
          unit: "g",
          group: "packaging",
          isRequired: true,
        },
        { name: "Shelf Life", slug: "shelf-life", type: "TEXT", group: "packaging" },
        {
          name: "Storage",
          slug: "storage",
          type: "SELECT",
          options: ["Room Temperature", "Refrigerated", "Frozen"],
          group: "packaging",
        },
        { name: "Organic", slug: "organic", type: "BOOLEAN", group: "dietary", isFilterable: true },
      ],
    },
  ],
};

// ─── INDUSTRIAL & TOOLS ─────────────────────────────────────────

export const industrialSector: SectorDefinition = {
  name: "Industrial & Tools",
  slug: "industrial",
  sector: "INDUSTRIAL",
  description: "Industrial equipment, tools, and machinery",
  attributeGroups: [
    { name: "Technical Specifications", slug: "tech-specs" },
    { name: "Power & Performance", slug: "power" },
    { name: "Safety & Compliance", slug: "safety" },
    { name: "Physical Dimensions", slug: "dimensions" },
  ],
  productTypes: [
    {
      name: "Power Tool",
      slug: "power-tool",
      description: "Electric and battery-powered tools",
      icon: "wrench",
      attributes: [
        {
          name: "Tool Type",
          slug: "tool-type",
          type: "SELECT",
          options: [
            "Drill",
            "Impact Driver",
            "Circular Saw",
            "Angle Grinder",
            "Sander",
            "Router",
            "Jigsaw",
            "Reciprocating Saw",
          ],
          group: "tech-specs",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Power Source",
          slug: "power-source",
          type: "SELECT",
          options: ["Corded (AC)", "Cordless (Battery)", "Pneumatic"],
          group: "power",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Voltage",
          slug: "voltage",
          type: "NUMBER",
          unit: "V",
          group: "power",
          isFilterable: true,
          showOnCard: true,
        },
        { name: "Wattage", slug: "wattage", type: "NUMBER", unit: "W", group: "power" },
        { name: "RPM", slug: "rpm", type: "NUMBER", unit: "rpm", group: "power" },
        {
          name: "Torque",
          slug: "torque",
          type: "NUMBER",
          unit: "Nm",
          group: "power",
          isFilterable: true,
        },
        {
          name: "Battery Capacity",
          slug: "battery-capacity",
          type: "NUMBER",
          unit: "Ah",
          group: "power",
        },
        {
          name: "Chuck Size",
          slug: "chuck-size",
          type: "SELECT",
          options: ["6mm", "10mm", "13mm", "16mm"],
          group: "tech-specs",
        },
        { name: "Weight", slug: "weight", type: "NUMBER", unit: "kg", group: "dimensions" },
        { name: "Noise Level", slug: "noise-level", type: "NUMBER", unit: "dB", group: "safety" },
        { name: "Vibration", slug: "vibration", type: "NUMBER", unit: "m/s²", group: "safety" },
        {
          name: "CE Certified",
          slug: "ce-certified",
          type: "BOOLEAN",
          group: "safety",
          isFilterable: true,
        },
        { name: "Warranty", slug: "warranty", type: "TEXT", group: "safety" },
        {
          name: "Professional Grade",
          slug: "professional",
          type: "BOOLEAN",
          group: "tech-specs",
          isFilterable: true,
        },
      ],
    },
    {
      name: "Safety Equipment",
      slug: "safety-equipment",
      description: "Personal protective equipment (PPE)",
      icon: "shield",
      attributes: [
        {
          name: "PPE Category",
          slug: "ppe-category",
          type: "SELECT",
          options: ["Head", "Eye", "Ear", "Respiratory", "Hand", "Body", "Foot", "Fall Protection"],
          group: "tech-specs",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Protection Class",
          slug: "protection-class",
          type: "TEXT",
          group: "safety",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Certification",
          slug: "certification",
          type: "MULTISELECT",
          options: ["EN 166", "EN 352", "EN 397", "EN ISO 20345", "EN 388", "EN ISO 374", "EN 149"],
          group: "safety",
          isFilterable: true,
        },
        {
          name: "Size",
          slug: "size",
          type: "SELECT",
          options: ["XS", "S", "M", "L", "XL", "XXL", "One Size"],
          group: "dimensions",
          isFilterable: true,
        },
        { name: "Material", slug: "material", type: "TEXT", group: "tech-specs" },
        {
          name: "Reusable",
          slug: "reusable",
          type: "BOOLEAN",
          group: "tech-specs",
          isFilterable: true,
        },
        {
          name: "High Visibility",
          slug: "high-vis",
          type: "BOOLEAN",
          group: "safety",
          isFilterable: true,
        },
        { name: "Color", slug: "color", type: "COLOR", group: "dimensions", isFilterable: true },
      ],
    },
  ],
};

// ─── HOME & GARDEN ──────────────────────────────────────────────

export const homeSector: SectorDefinition = {
  name: "Home & Garden",
  slug: "home-garden",
  sector: "HOME",
  description: "Furniture, decor, garden, and household items",
  attributeGroups: [
    { name: "Dimensions", slug: "dimensions" },
    { name: "Material & Finish", slug: "material" },
    { name: "Room & Placement", slug: "room" },
    { name: "Features", slug: "features" },
    { name: "Cooking & Heat", slug: "cooking" },
  ],
  productTypes: [
    {
      name: "Furniture",
      slug: "furniture",
      description: "Tables, chairs, sofas, and more",
      icon: "sofa",
      attributes: [
        {
          name: "Furniture Type",
          slug: "furniture-type",
          type: "SELECT",
          options: ["Table", "Chair", "Sofa", "Bed", "Desk", "Shelf", "Cabinet", "Dresser"],
          group: "room",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Width",
          slug: "width",
          type: "NUMBER",
          unit: "cm",
          group: "dimensions",
          isRequired: true,
        },
        {
          name: "Height",
          slug: "height",
          type: "NUMBER",
          unit: "cm",
          group: "dimensions",
          isRequired: true,
        },
        {
          name: "Depth",
          slug: "depth",
          type: "NUMBER",
          unit: "cm",
          group: "dimensions",
          isRequired: true,
        },
        { name: "Weight", slug: "weight", type: "NUMBER", unit: "kg", group: "dimensions" },
        {
          name: "Material",
          slug: "material",
          type: "SELECT",
          options: [
            "Solid Wood",
            "MDF",
            "Metal",
            "Glass",
            "Rattan",
            "Upholstered",
            "Marble",
            "Plastic",
          ],
          group: "material",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Finish",
          slug: "finish",
          type: "SELECT",
          options: ["Natural", "Painted", "Lacquered", "Oiled", "Stained", "Chrome", "Brass"],
          group: "material",
          isFilterable: true,
        },
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "material",
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Room",
          slug: "room-type",
          type: "MULTISELECT",
          options: ["Living Room", "Bedroom", "Kitchen", "Dining", "Office", "Bathroom", "Outdoor"],
          group: "room",
          isFilterable: true,
        },
        { name: "Assembly Required", slug: "assembly", type: "BOOLEAN", group: "features" },
        { name: "Max Load", slug: "max-load", type: "NUMBER", unit: "kg", group: "features" },
        {
          name: "Seating Capacity",
          slug: "seating",
          type: "NUMBER",
          group: "features",
          isFilterable: true,
        },
      ],
    },
    {
      name: "Lighting",
      slug: "lighting",
      description: "Lamps, fixtures, and smart lighting",
      icon: "lamp",
      attributes: [
        {
          name: "Light Type",
          slug: "light-type",
          type: "SELECT",
          options: [
            "Table Lamp",
            "Floor Lamp",
            "Pendant",
            "Ceiling",
            "Wall Sconce",
            "Spotlight",
            "LED Strip",
          ],
          group: "features",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Bulb Type",
          slug: "bulb-type",
          type: "SELECT",
          options: ["LED", "Halogen", "Incandescent", "Integrated LED"],
          group: "features",
          isRequired: true,
          isFilterable: true,
        },
        { name: "Wattage", slug: "wattage", type: "NUMBER", unit: "W", group: "features" },
        {
          name: "Lumens",
          slug: "lumens",
          type: "NUMBER",
          unit: "lm",
          group: "features",
          isFilterable: true,
        },
        {
          name: "Color Temperature",
          slug: "color-temp",
          type: "SELECT",
          options: ["Warm White (2700K)", "Neutral (4000K)", "Daylight (5000K)", "Adjustable"],
          group: "features",
          isFilterable: true,
        },
        {
          name: "Dimmable",
          slug: "dimmable",
          type: "BOOLEAN",
          group: "features",
          isFilterable: true,
        },
        {
          name: "Smart Compatible",
          slug: "smart",
          type: "BOOLEAN",
          group: "features",
          isFilterable: true,
        },
        { name: "Height", slug: "height", type: "NUMBER", unit: "cm", group: "dimensions" },
        { name: "Width", slug: "width", type: "NUMBER", unit: "cm", group: "dimensions" },
        {
          name: "Material",
          slug: "material",
          type: "SELECT",
          options: ["Metal", "Glass", "Fabric", "Wood", "Rattan", "Concrete", "Ceramic"],
          group: "material",
          isFilterable: true,
        },
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "material",
          isFilterable: true,
          showOnCard: true,
        },
      ],
    },
    {
      name: "Cookware",
      slug: "cookware",
      description: "Pots, pans, bakeware, and cooking vessels",
      icon: "cooking-pot",
      attributes: [
        // Dimensions
        {
          name: "Diameter",
          slug: "diameter",
          type: "NUMBER",
          unit: "cm",
          group: "dimensions",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Height",
          slug: "height",
          type: "NUMBER",
          unit: "cm",
          group: "dimensions",
          isRequired: true,
        },
        { name: "Depth", slug: "depth", type: "NUMBER", unit: "cm", group: "dimensions" },
        {
          name: "Capacity",
          slug: "capacity",
          type: "NUMBER",
          unit: "L",
          group: "dimensions",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        { name: "Weight", slug: "weight", type: "NUMBER", unit: "kg", group: "dimensions" },
        // Material
        {
          name: "Body Material",
          slug: "body-material",
          type: "SELECT",
          options: [
            "Stainless Steel",
            "Cast Iron",
            "Carbon Steel",
            "Aluminum",
            "Hard-Anodized Aluminum",
            "Copper",
            "Ceramic",
            "Clay/Terracotta",
            "Enameled Cast Iron",
            "Titanium",
            "Glass",
          ],
          group: "material",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Material Thickness",
          slug: "material-thickness",
          type: "NUMBER",
          unit: "mm",
          group: "material",
        },
        {
          name: "Interior Coating",
          slug: "interior-coating",
          type: "SELECT",
          options: [
            "None (Uncoated)",
            "Non-Stick (PTFE)",
            "Ceramic Non-Stick",
            "Enamel",
            "Seasoned",
            "Diamond Coating",
            "Titanium Coating",
            "Granite Coating",
          ],
          group: "material",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Exterior Finish",
          slug: "exterior-finish",
          type: "SELECT",
          options: ["Polished", "Brushed/Satin", "Matte", "Enameled", "Hammered", "Powder Coated"],
          group: "material",
        },
        {
          name: "Surface Texture",
          slug: "surface-texture",
          type: "SELECT",
          options: ["Smooth", "Textured/Honeycomb", "Ridged/Grill", "Dimpled", "Hammered"],
          group: "material",
          isFilterable: true,
        },
        {
          name: "Handle Material",
          slug: "handle-material",
          type: "SELECT",
          options: [
            "Stainless Steel",
            "Bakelite",
            "Silicone",
            "Wood",
            "Cast Iron (Integral)",
            "Stay-Cool Steel",
            "Riveted Steel",
          ],
          group: "material",
        },
        {
          name: "Lid Material",
          slug: "lid-material",
          type: "SELECT",
          options: ["Glass", "Stainless Steel", "Cast Iron", "Ceramic", "No Lid Included"],
          group: "material",
        },
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "material",
          isFilterable: true,
          showOnCard: true,
        },
        // Cooking & Heat
        {
          name: "Cookware Type",
          slug: "cookware-type",
          type: "SELECT",
          options: [
            "Saucepan",
            "Stockpot",
            "Frying Pan/Skillet",
            "Sauté Pan",
            "Dutch Oven",
            "Wok",
            "Casserole",
            "Roasting Pan",
            "Grill Pan",
            "Baking Sheet",
            "Tagine",
            "Pressure Cooker",
          ],
          group: "cooking",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Compatible Hobs",
          slug: "compatible-hobs",
          type: "MULTISELECT",
          options: ["Gas", "Electric", "Ceramic", "Induction", "Halogen", "Open Fire", "BBQ/Grill"],
          group: "cooking",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Oven Safe",
          slug: "oven-safe",
          type: "BOOLEAN",
          group: "cooking",
          isFilterable: true,
        },
        {
          name: "Max Oven Temperature",
          slug: "max-oven-temp",
          type: "NUMBER",
          unit: "°C",
          group: "cooking",
        },
        { name: "Broiler Safe", slug: "broiler-safe", type: "BOOLEAN", group: "cooking" },
        { name: "Freezer Safe", slug: "freezer-safe", type: "BOOLEAN", group: "cooking" },
        // Features
        {
          name: "Dishwasher Safe",
          slug: "dishwasher-safe",
          type: "BOOLEAN",
          group: "features",
          isFilterable: true,
        },
        {
          name: "PFOA Free",
          slug: "pfoa-free",
          type: "BOOLEAN",
          group: "features",
          isFilterable: true,
        },
        {
          name: "PFAS Free",
          slug: "pfas-free",
          type: "BOOLEAN",
          group: "features",
          isFilterable: true,
        },
        { name: "Pour Spout", slug: "pour-spout", type: "BOOLEAN", group: "features" },
        {
          name: "Measurement Markings",
          slug: "measurement-markings",
          type: "BOOLEAN",
          group: "features",
        },
        {
          name: "Country of Manufacture",
          slug: "made-in",
          type: "TEXT",
          group: "features",
          isFilterable: true,
        },
        { name: "Warranty", slug: "warranty", type: "TEXT", group: "features" },
      ],
    },
    {
      name: "Home Decor",
      slug: "home-decor",
      description: "Vases, cushions, rugs, candles, and decorative items",
      icon: "flower",
      attributes: [
        // Dimensions
        {
          name: "Width",
          slug: "width",
          type: "NUMBER",
          unit: "cm",
          group: "dimensions",
          isRequired: true,
        },
        {
          name: "Height",
          slug: "height",
          type: "NUMBER",
          unit: "cm",
          group: "dimensions",
          isRequired: true,
        },
        { name: "Depth/Diameter", slug: "depth", type: "NUMBER", unit: "cm", group: "dimensions" },
        { name: "Weight", slug: "weight", type: "NUMBER", unit: "kg", group: "dimensions" },
        // Material
        {
          name: "Primary Material",
          slug: "primary-material",
          type: "SELECT",
          options: [
            "Ceramic",
            "Glass",
            "Wood",
            "Metal",
            "Fabric/Textile",
            "Stone/Marble",
            "Rattan/Wicker",
            "Concrete",
            "Resin",
            "Terracotta",
            "Porcelain",
            "Leather",
            "Paper/Cardboard",
            "Crystal",
            "Wax",
          ],
          group: "material",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Material Finish",
          slug: "material-finish",
          type: "SELECT",
          options: [
            "Matte",
            "Glossy",
            "Satin",
            "Textured",
            "Brushed",
            "Hammered",
            "Patina",
            "Raw/Natural",
            "Painted",
            "Glazed",
            "Frosted",
            "Distressed",
          ],
          group: "material",
          isFilterable: true,
        },
        {
          name: "Surface Texture",
          slug: "surface-texture",
          type: "SELECT",
          options: [
            "Smooth",
            "Ribbed",
            "Woven",
            "Knitted",
            "Embossed",
            "Carved",
            "Rough/Natural",
            "Fluted",
            "Pebbled",
            "Crackle Glaze",
          ],
          group: "material",
          isFilterable: true,
        },
        {
          name: "Color",
          slug: "color",
          type: "COLOR",
          group: "material",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Color Name",
          slug: "color-name",
          type: "TEXT",
          group: "material",
          isSearchable: true,
        },
        // Room & Placement
        {
          name: "Decor Type",
          slug: "decor-type",
          type: "SELECT",
          options: [
            "Vase",
            "Cushion/Pillow",
            "Rug",
            "Candle",
            "Wall Art",
            "Mirror",
            "Planter",
            "Tray",
            "Sculpture/Figurine",
            "Photo Frame",
            "Clock",
            "Bookend",
            "Basket",
          ],
          group: "room",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Room",
          slug: "room-type",
          type: "MULTISELECT",
          options: [
            "Living Room",
            "Bedroom",
            "Kitchen",
            "Dining",
            "Bathroom",
            "Office",
            "Hallway",
            "Outdoor/Patio",
          ],
          group: "room",
          isFilterable: true,
        },
        {
          name: "Placement",
          slug: "placement",
          type: "SELECT",
          options: [
            "Tabletop",
            "Floor",
            "Wall",
            "Shelf",
            "Hanging",
            "Window Sill",
            "Mantle",
            "Console",
          ],
          group: "room",
        },
        {
          name: "Style",
          slug: "style",
          type: "SELECT",
          options: [
            "Modern",
            "Minimalist",
            "Bohemian",
            "Scandinavian",
            "Industrial",
            "Rustic",
            "Coastal",
            "Traditional",
            "Art Deco",
            "Mid-Century",
            "Japandi",
            "Farmhouse",
          ],
          group: "room",
          isFilterable: true,
        },
        // Features
        { name: "Waterproof", slug: "waterproof", type: "BOOLEAN", group: "features" },
        {
          name: "Outdoor Suitable",
          slug: "outdoor-suitable",
          type: "BOOLEAN",
          group: "features",
          isFilterable: true,
        },
        {
          name: "Handmade",
          slug: "handmade",
          type: "BOOLEAN",
          group: "features",
          isFilterable: true,
        },
        {
          name: "Fragrance (candles)",
          slug: "fragrance",
          type: "TEXT",
          group: "features",
          isSearchable: true,
        },
        {
          name: "Burn Time (candles)",
          slug: "burn-time",
          type: "NUMBER",
          unit: "hours",
          group: "features",
        },
        {
          name: "Fill Material (cushions)",
          slug: "fill-material",
          type: "SELECT",
          options: [
            "Polyester Fiber",
            "Down",
            "Down Alternative",
            "Foam",
            "Memory Foam",
            "Buckwheat",
          ],
          group: "features",
        },
        {
          name: "Pile Height (rugs)",
          slug: "pile-height",
          type: "SELECT",
          options: ["Flatweave", "Low Pile", "Medium Pile", "High Pile/Shag"],
          group: "features",
        },
        { name: "Care Instructions", slug: "care-instructions", type: "TEXT", group: "features" },
      ],
    },
  ],
};

// ─── BEAUTY & COSMETICS ─────────────────────────────────────────

export const beautySector: SectorDefinition = {
  name: "Beauty & Cosmetics",
  slug: "beauty",
  sector: "BEAUTY",
  description: "Skincare, makeup, haircare, and personal care",
  attributeGroups: [
    { name: "Product Details", slug: "product-details" },
    { name: "Ingredients & Formula", slug: "formula" },
    { name: "Suitability", slug: "suitability" },
    { name: "Usage", slug: "usage" },
  ],
  productTypes: [
    {
      name: "Skincare",
      slug: "skincare",
      description: "Face and body skincare products",
      icon: "droplet",
      attributes: [
        {
          name: "Product Type",
          slug: "product-type",
          type: "SELECT",
          options: [
            "Cleanser",
            "Toner",
            "Serum",
            "Moisturizer",
            "Sunscreen",
            "Mask",
            "Eye Cream",
            "Exfoliator",
            "Oil",
          ],
          group: "product-details",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Skin Type",
          slug: "skin-type",
          type: "MULTISELECT",
          options: ["Normal", "Dry", "Oily", "Combination", "Sensitive", "Mature"],
          group: "suitability",
          isRequired: true,
          isFilterable: true,
        },
        {
          name: "Skin Concern",
          slug: "skin-concern",
          type: "MULTISELECT",
          options: [
            "Acne",
            "Aging",
            "Dark Spots",
            "Dullness",
            "Redness",
            "Dryness",
            "Pores",
            "Wrinkles",
          ],
          group: "suitability",
          isFilterable: true,
        },
        {
          name: "Key Ingredients",
          slug: "key-ingredients",
          type: "MULTISELECT",
          options: [
            "Retinol",
            "Vitamin C",
            "Niacinamide",
            "Hyaluronic Acid",
            "Salicylic Acid",
            "AHA/BHA",
            "Peptides",
            "Ceramides",
            "SPF",
          ],
          group: "formula",
          isFilterable: true,
        },
        {
          name: "Volume",
          slug: "volume",
          type: "NUMBER",
          unit: "ml",
          group: "product-details",
          isRequired: true,
        },
        { name: "SPF", slug: "spf", type: "NUMBER", group: "formula", isFilterable: true },
        {
          name: "Fragrance Free",
          slug: "fragrance-free",
          type: "BOOLEAN",
          group: "formula",
          isFilterable: true,
        },
        {
          name: "Cruelty Free",
          slug: "cruelty-free",
          type: "BOOLEAN",
          group: "formula",
          isFilterable: true,
        },
        { name: "Vegan", slug: "vegan", type: "BOOLEAN", group: "formula", isFilterable: true },
        {
          name: "Application",
          slug: "application",
          type: "SELECT",
          options: ["AM", "PM", "AM & PM"],
          group: "usage",
        },
      ],
    },
    {
      name: "Makeup",
      slug: "makeup",
      description: "Color cosmetics and makeup",
      icon: "palette",
      attributes: [
        {
          name: "Product Type",
          slug: "product-type",
          type: "SELECT",
          options: [
            "Foundation",
            "Concealer",
            "Powder",
            "Blush",
            "Bronzer",
            "Highlighter",
            "Lipstick",
            "Eyeshadow",
            "Mascara",
            "Eyeliner",
            "Brow",
          ],
          group: "product-details",
          isRequired: true,
          isFilterable: true,
          showOnCard: true,
        },
        {
          name: "Shade",
          slug: "shade",
          type: "TEXT",
          group: "product-details",
          isRequired: true,
          isSearchable: true,
        },
        {
          name: "Undertone",
          slug: "undertone",
          type: "SELECT",
          options: ["Cool", "Warm", "Neutral"],
          group: "suitability",
          isFilterable: true,
        },
        {
          name: "Coverage",
          slug: "coverage",
          type: "SELECT",
          options: ["Sheer", "Light", "Medium", "Full"],
          group: "product-details",
          isFilterable: true,
        },
        {
          name: "Finish",
          slug: "finish",
          type: "SELECT",
          options: ["Matte", "Dewy", "Satin", "Natural", "Shimmer", "Metallic", "Glitter"],
          group: "product-details",
          isFilterable: true,
        },
        {
          name: "Skin Type",
          slug: "skin-type",
          type: "MULTISELECT",
          options: ["Normal", "Dry", "Oily", "Combination", "Sensitive"],
          group: "suitability",
          isFilterable: true,
        },
        {
          name: "Waterproof",
          slug: "waterproof",
          type: "BOOLEAN",
          group: "product-details",
          isFilterable: true,
        },
        { name: "Long-Wearing", slug: "long-wearing", type: "BOOLEAN", group: "product-details" },
        {
          name: "Cruelty Free",
          slug: "cruelty-free",
          type: "BOOLEAN",
          group: "formula",
          isFilterable: true,
        },
        { name: "Vegan", slug: "vegan", type: "BOOLEAN", group: "formula", isFilterable: true },
      ],
    },
  ],
};

// ─── ALL SECTORS ────────────────────────────────────────────────

export const allSectors: SectorDefinition[] = [
  electronicsSector,
  fashionSector,
  foodSector,
  industrialSector,
  homeSector,
  beautySector,
];

export function getSectorBySlug(slug: string): SectorDefinition | undefined {
  return allSectors.find((s) => s.slug === slug);
}

export function getProductTypeBySlug(slug: string): ProductTypeTemplate | undefined {
  for (const sector of allSectors) {
    const pt = sector.productTypes.find((t) => t.slug === slug);
    if (pt) return pt;
  }
  return undefined;
}
